YAML 
name: Streamlit Keep Alive 

on:   
	schedule:     
	- cron: '0 0,12 * * *' # 12시간마다 자동 실행   
	workflow_dispatch:      # 수동 실행 허용

 jobs:   
	auto_commit:    
		 runs-on: ubuntu-latest     
		
	permissions:    
	contents: write     

	steps:      

		 - uses: actions/checkout@v4       
		- name: Create empty commit        
	 run: |           
		git config --local user.email "github-actions[bot]@users.noreply.github.com"           
		git config --local user.name "github-actions[bot]"           
		git commit --allow-empty -m "Keep alive: Prevent Streamlit sleep mode"           
		git push
