name: Keep Streamlit App Awake

on:
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Streamlit app
        run: curl -s -o /dev/null -w "응답 코드: %{http_code}\n" https://sudoku-6lzzbwyx5nrbmml5awpuqg.streamlit.app
